/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AlbumsImport } from './routes/albums'
import { Route as IndexImport } from './routes/index'
import { Route as AlbumsIndexImport } from './routes/albums/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AlbumsSearchImport } from './routes/albums/search'
import { Route as AlbumsReviewsImport } from './routes/albums/reviews'
import { Route as AlbumsBookmarksImport } from './routes/albums/bookmarks'
import { Route as AlbumsAlbumIdImport } from './routes/albums/$albumId'
import { Route as AlbumsAlbumIdIndexImport } from './routes/albums/$albumId/index'
import { Route as AlbumsAlbumIdEditImport } from './routes/albums/$albumId/edit'
import { Route as AlbumsAlbumIdReviewIndexImport } from './routes/albums/$albumId/review/index'
import { Route as AlbumsAlbumIdReviewReviewIdImport } from './routes/albums/$albumId/review/$reviewId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsRoute = AlbumsImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsIndexRoute = AlbumsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumsRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const AlbumsSearchRoute = AlbumsSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AlbumsRoute,
} as any)

const AlbumsReviewsRoute = AlbumsReviewsImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AlbumsRoute,
} as any)

const AlbumsBookmarksRoute = AlbumsBookmarksImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AlbumsRoute,
} as any)

const AlbumsAlbumIdRoute = AlbumsAlbumIdImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AlbumsRoute,
} as any)

const AlbumsAlbumIdIndexRoute = AlbumsAlbumIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumsAlbumIdRoute,
} as any)

const AlbumsAlbumIdEditRoute = AlbumsAlbumIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AlbumsAlbumIdRoute,
} as any)

const AlbumsAlbumIdReviewIndexRoute = AlbumsAlbumIdReviewIndexImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AlbumsAlbumIdRoute,
} as any)

const AlbumsAlbumIdReviewReviewIdRoute =
  AlbumsAlbumIdReviewReviewIdImport.update({
    id: '/review/$reviewId',
    path: '/review/$reviewId',
    getParentRoute: () => AlbumsAlbumIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdImport
      parentRoute: typeof AlbumsImport
    }
    '/albums/bookmarks': {
      id: '/albums/bookmarks'
      path: '/bookmarks'
      fullPath: '/albums/bookmarks'
      preLoaderRoute: typeof AlbumsBookmarksImport
      parentRoute: typeof AlbumsImport
    }
    '/albums/reviews': {
      id: '/albums/reviews'
      path: '/reviews'
      fullPath: '/albums/reviews'
      preLoaderRoute: typeof AlbumsReviewsImport
      parentRoute: typeof AlbumsImport
    }
    '/albums/search': {
      id: '/albums/search'
      path: '/search'
      fullPath: '/albums/search'
      preLoaderRoute: typeof AlbumsSearchImport
      parentRoute: typeof AlbumsImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexImport
      parentRoute: typeof AlbumsImport
    }
    '/albums/$albumId/edit': {
      id: '/albums/$albumId/edit'
      path: '/edit'
      fullPath: '/albums/$albumId/edit'
      preLoaderRoute: typeof AlbumsAlbumIdEditImport
      parentRoute: typeof AlbumsAlbumIdImport
    }
    '/albums/$albumId/': {
      id: '/albums/$albumId/'
      path: '/'
      fullPath: '/albums/$albumId/'
      preLoaderRoute: typeof AlbumsAlbumIdIndexImport
      parentRoute: typeof AlbumsAlbumIdImport
    }
    '/albums/$albumId/review/$reviewId': {
      id: '/albums/$albumId/review/$reviewId'
      path: '/review/$reviewId'
      fullPath: '/albums/$albumId/review/$reviewId'
      preLoaderRoute: typeof AlbumsAlbumIdReviewReviewIdImport
      parentRoute: typeof AlbumsAlbumIdImport
    }
    '/albums/$albumId/review/': {
      id: '/albums/$albumId/review/'
      path: '/review'
      fullPath: '/albums/$albumId/review'
      preLoaderRoute: typeof AlbumsAlbumIdReviewIndexImport
      parentRoute: typeof AlbumsAlbumIdImport
    }
  }
}

// Create and export the route tree

interface AlbumsAlbumIdRouteChildren {
  AlbumsAlbumIdEditRoute: typeof AlbumsAlbumIdEditRoute
  AlbumsAlbumIdIndexRoute: typeof AlbumsAlbumIdIndexRoute
  AlbumsAlbumIdReviewReviewIdRoute: typeof AlbumsAlbumIdReviewReviewIdRoute
  AlbumsAlbumIdReviewIndexRoute: typeof AlbumsAlbumIdReviewIndexRoute
}

const AlbumsAlbumIdRouteChildren: AlbumsAlbumIdRouteChildren = {
  AlbumsAlbumIdEditRoute: AlbumsAlbumIdEditRoute,
  AlbumsAlbumIdIndexRoute: AlbumsAlbumIdIndexRoute,
  AlbumsAlbumIdReviewReviewIdRoute: AlbumsAlbumIdReviewReviewIdRoute,
  AlbumsAlbumIdReviewIndexRoute: AlbumsAlbumIdReviewIndexRoute,
}

const AlbumsAlbumIdRouteWithChildren = AlbumsAlbumIdRoute._addFileChildren(
  AlbumsAlbumIdRouteChildren,
)

interface AlbumsRouteChildren {
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRouteWithChildren
  AlbumsBookmarksRoute: typeof AlbumsBookmarksRoute
  AlbumsReviewsRoute: typeof AlbumsReviewsRoute
  AlbumsSearchRoute: typeof AlbumsSearchRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsAlbumIdRoute: AlbumsAlbumIdRouteWithChildren,
  AlbumsBookmarksRoute: AlbumsBookmarksRoute,
  AlbumsReviewsRoute: AlbumsReviewsRoute,
  AlbumsSearchRoute: AlbumsSearchRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/albums/$albumId': typeof AlbumsAlbumIdRouteWithChildren
  '/albums/bookmarks': typeof AlbumsBookmarksRoute
  '/albums/reviews': typeof AlbumsReviewsRoute
  '/albums/search': typeof AlbumsSearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/albums/': typeof AlbumsIndexRoute
  '/albums/$albumId/edit': typeof AlbumsAlbumIdEditRoute
  '/albums/$albumId/': typeof AlbumsAlbumIdIndexRoute
  '/albums/$albumId/review/$reviewId': typeof AlbumsAlbumIdReviewReviewIdRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/albums/bookmarks': typeof AlbumsBookmarksRoute
  '/albums/reviews': typeof AlbumsReviewsRoute
  '/albums/search': typeof AlbumsSearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/albums': typeof AlbumsIndexRoute
  '/albums/$albumId/edit': typeof AlbumsAlbumIdEditRoute
  '/albums/$albumId': typeof AlbumsAlbumIdIndexRoute
  '/albums/$albumId/review/$reviewId': typeof AlbumsAlbumIdReviewReviewIdRoute
  '/albums/$albumId/review': typeof AlbumsAlbumIdReviewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/albums/$albumId': typeof AlbumsAlbumIdRouteWithChildren
  '/albums/bookmarks': typeof AlbumsBookmarksRoute
  '/albums/reviews': typeof AlbumsReviewsRoute
  '/albums/search': typeof AlbumsSearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/albums/': typeof AlbumsIndexRoute
  '/albums/$albumId/edit': typeof AlbumsAlbumIdEditRoute
  '/albums/$albumId/': typeof AlbumsAlbumIdIndexRoute
  '/albums/$albumId/review/$reviewId': typeof AlbumsAlbumIdReviewReviewIdRoute
  '/albums/$albumId/review/': typeof AlbumsAlbumIdReviewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/auth'
    | '/albums/$albumId'
    | '/albums/bookmarks'
    | '/albums/reviews'
    | '/albums/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/albums/'
    | '/albums/$albumId/edit'
    | '/albums/$albumId/'
    | '/albums/$albumId/review/$reviewId'
    | '/albums/$albumId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/albums/bookmarks'
    | '/albums/reviews'
    | '/albums/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/albums'
    | '/albums/$albumId/edit'
    | '/albums/$albumId'
    | '/albums/$albumId/review/$reviewId'
    | '/albums/$albumId/review'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/auth'
    | '/albums/$albumId'
    | '/albums/bookmarks'
    | '/albums/reviews'
    | '/albums/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/albums/'
    | '/albums/$albumId/edit'
    | '/albums/$albumId/'
    | '/albums/$albumId/review/$reviewId'
    | '/albums/$albumId/review/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/albums",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/albums": {
      "filePath": "albums.tsx",
      "children": [
        "/albums/$albumId",
        "/albums/bookmarks",
        "/albums/reviews",
        "/albums/search",
        "/albums/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/albums/$albumId": {
      "filePath": "albums/$albumId.tsx",
      "parent": "/albums",
      "children": [
        "/albums/$albumId/edit",
        "/albums/$albumId/",
        "/albums/$albumId/review/$reviewId",
        "/albums/$albumId/review/"
      ]
    },
    "/albums/bookmarks": {
      "filePath": "albums/bookmarks.tsx",
      "parent": "/albums"
    },
    "/albums/reviews": {
      "filePath": "albums/reviews.tsx",
      "parent": "/albums"
    },
    "/albums/search": {
      "filePath": "albums/search.tsx",
      "parent": "/albums"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/auth"
    },
    "/albums/": {
      "filePath": "albums/index.tsx",
      "parent": "/albums"
    },
    "/albums/$albumId/edit": {
      "filePath": "albums/$albumId/edit.tsx",
      "parent": "/albums/$albumId"
    },
    "/albums/$albumId/": {
      "filePath": "albums/$albumId/index.tsx",
      "parent": "/albums/$albumId"
    },
    "/albums/$albumId/review/$reviewId": {
      "filePath": "albums/$albumId/review/$reviewId.tsx",
      "parent": "/albums/$albumId"
    },
    "/albums/$albumId/review/": {
      "filePath": "albums/$albumId/review/index.tsx",
      "parent": "/albums/$albumId"
    }
  }
}
ROUTE_MANIFEST_END */
