/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReviewsImport } from './routes/reviews'
import { Route as AuthImport } from './routes/auth'
import { Route as AlbumsImport } from './routes/albums'
import { Route as IndexImport } from './routes/index'
import { Route as ReviewsIndexImport } from './routes/reviews/index'
import { Route as AlbumsIndexImport } from './routes/albums/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AlbumsSearchImport } from './routes/albums/search'
import { Route as AlbumsAlbumIdIndexImport } from './routes/albums/$albumId/index'

// Create/Update Routes

const ReviewsRoute = ReviewsImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsRoute = AlbumsImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReviewsIndexRoute = ReviewsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsRoute,
} as any)

const AlbumsIndexRoute = AlbumsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumsRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const AlbumsSearchRoute = AlbumsSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AlbumsRoute,
} as any)

const AlbumsAlbumIdIndexRoute = AlbumsAlbumIdIndexImport.update({
  id: '/$albumId/',
  path: '/$albumId/',
  getParentRoute: () => AlbumsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsImport
      parentRoute: typeof rootRoute
    }
    '/albums/search': {
      id: '/albums/search'
      path: '/search'
      fullPath: '/albums/search'
      preLoaderRoute: typeof AlbumsSearchImport
      parentRoute: typeof AlbumsImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexImport
      parentRoute: typeof AlbumsImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexImport
      parentRoute: typeof ReviewsImport
    }
    '/albums/$albumId/': {
      id: '/albums/$albumId/'
      path: '/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdIndexImport
      parentRoute: typeof AlbumsImport
    }
  }
}

// Create and export the route tree

interface AlbumsRouteChildren {
  AlbumsSearchRoute: typeof AlbumsSearchRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  AlbumsAlbumIdIndexRoute: typeof AlbumsAlbumIdIndexRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsSearchRoute: AlbumsSearchRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  AlbumsAlbumIdIndexRoute: AlbumsAlbumIdIndexRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ReviewsRouteChildren {
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsIndexRoute: ReviewsIndexRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/albums/search': typeof AlbumsSearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/albums/': typeof AlbumsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/albums/$albumId': typeof AlbumsAlbumIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/albums/search': typeof AlbumsSearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/albums': typeof AlbumsIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/albums/$albumId': typeof AlbumsAlbumIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/albums/search': typeof AlbumsSearchRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/albums/': typeof AlbumsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/albums/$albumId/': typeof AlbumsAlbumIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/auth'
    | '/reviews'
    | '/albums/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/albums/'
    | '/reviews/'
    | '/albums/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/albums/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/albums'
    | '/reviews'
    | '/albums/$albumId'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/auth'
    | '/reviews'
    | '/albums/search'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/albums/'
    | '/reviews/'
    | '/albums/$albumId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ReviewsRoute: typeof ReviewsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ReviewsRoute: ReviewsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/albums",
        "/auth",
        "/reviews"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/albums": {
      "filePath": "albums.tsx",
      "children": [
        "/albums/search",
        "/albums/",
        "/albums/$albumId/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/reviews": {
      "filePath": "reviews.tsx",
      "children": [
        "/reviews/"
      ]
    },
    "/albums/search": {
      "filePath": "albums/search.tsx",
      "parent": "/albums"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/auth"
    },
    "/albums/": {
      "filePath": "albums/index.tsx",
      "parent": "/albums"
    },
    "/reviews/": {
      "filePath": "reviews/index.tsx",
      "parent": "/reviews"
    },
    "/albums/$albumId/": {
      "filePath": "albums/$albumId/index.tsx",
      "parent": "/albums"
    }
  }
}
ROUTE_MANIFEST_END */
